!THIS PROGRAM CONVERT HEXADECIMAL INTO DECIMAL NUMBER
PROGRAM HEX_TO_DEC
 IMPLICIT NONE
 INTEGER::DEC=0,I,J,L,CONV
 INTEGER::DIG(0:100)
 CHARACTER(LEN=10)::HEX
 CHARACTER(LEN=1)::HEX_DIG
DO I=0,100
DIG(I)=0
END DO
PRINT*,"ENTER A HEXADECIMAL NUMBER"
READ*,HEX
L=LEN_TRIM(HEX)
HEX=TRIM(HEX)
!FINDING THE COEFFICIENTS
DO I=0,L-1
DIG(I)=CONV(HEX((I+1):(I+1)))
PRINT*,DIG(I)
END DO
J=L-1
print*,"length=",L
DO I=0,(L-1)
DEC=DEC+DIG(I)*(16**J)
J=J-1
END DO

PRINT*,"THE DECIMAL EQUIVALENT NUMBER:",DEC
END PROGRAM HEX_TO_DEC
 

INTEGER FUNCTION CONV(X)
 IMPLICIT NONE
 CHARACTER(LEN=1),INTENT(IN)::X
 SELECT CASE(X)
  CASE("0")
    CONV=0
  CASE("1")
    CONV=1
  CASE("2")
    CONV=2
  CASE("3")
    CONV=3
  CASE("4")
    CONV=4
  CASE("5")
    CONV=5
  CASE("6")
    CONV=6
  CASE("7")
    CONV=7
  CASE("8")
    CONV=8
  CASE("9")
    CONV=9
  CASE("A")
    CONV=10
  CASE("B")
    CONV=11
  CASE("C")
    CONV=12
  CASE("D")
    CONV=13
  CASE("E")
    CONV=14
  CASE("F")
    CONV=15
END SELECT
END FUNCTION CONV

